model:
  
data:
    batchsize: 64

training:
    training_epoch: 3000
    lr: 0.0001
    betas: [0.9,0.999]
    early_stop: True
    early_stop_settings:
        monitor: 'val_loss'
        patience: 200
        verbose: 1


    
        